### PR TITLE
Issue 192: add toleration support for bookie pods

### LINKED ISSUE #192: Add tolerations for bookie pods
### Description

It'd be useful to allow specifying pod tolerations for the bookie pods.

### Importance

I'd like to dedicate some nodes in a cluster to run only Pravega related workloads. Affinities can be used to schedule pods onto the dedicated nodes, but node taints seem the best way to prevent other non-Pravega-related pods from using them. To do this, I'd need to add tolerations for the bookie pods.

### Location

This would require adding controller & segment store pod tolerations to the Bookkeeper cluster spec. Additionally, it'd make sense to allow the Pravega helm chart to allow specifying the tolerations as well.

### PR DESCRIPTION
**Pull request by alfred-landrum**
Signed-off-by: Alfred Landrum <alfred@leakybucket.org>

### Change log description

Allow specifying tolerations for the bookie pods.

### Purpose of the change

Closes #192

### CODE REVIEW

**Comment by anishakj** [comment]
@alfred-landrum Could you please create a PR in https://github.com/pravega/charts for chart changes?

**Comment by alfred-landrum** [comment]
> @alfred-landrum Could you please create a PR in https://github.com/pravega/charts for chart changes?

will do!

**Comment by anishakj** [comment]
@alfred-landrum  Could you please resolve the conflicts

**Comment by alfred-landrum** [comment]
Part of a group of PR's to support pod tolerations:

bookkeeper operator:
https://github.com/pravega/bookkeeper-operator/pull/193

pravega operator:
https://github.com/pravega/pravega-operator/pull/608

charts:
https://github.com/pravega/charts/pull/117

**Comment by anishakj** [comment]
@alfred-landrum Could you please generate the deep copy file using the command

```
controller-gen object paths="./..."
```

**Comment by alfred-landrum** [comment]
@anishakj : done in https://github.com/pravega/bookkeeper-operator/pull/193/commits/ca75145e96c53438be61b16b6fcc7dfaf12fdc3b , though the change is minimal.

**Review by anishakj — APPROVED** [review]
LGTM

**Pull request merged**
